---
- hosts: server1
  become: yes
  become_method: sudo
  remote_user: ubuntu

  vars:
    service_name: jwt-authentication-service
    local_jar_path: /home/ubuntu/workspace/Microservice-Dev/Backend/Microservices/JWTAuthenticationManagement/target/JWTAuthenticationManagement-0.0.1-SNAPSHOT.jar
    remote_jar_path: /opt/webapp/JWTAuthenticationManagement-0.0.1-SNAPSHOT.jar
    remote_jar_directory: /opt/webapp
    systemd_service_file: /etc/systemd/system/{{ service_name }}.service

  tasks:
#    - name: Update apt packages
#      apt:
#        update_cache: yes
#        cache_valid_time: 86400

    - name: Create application directory
      file:
        path: "{{ remote_jar_directory }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy the JAR file to the production server
      copy:
        src: "{{ local_jar_path }}"
        dest: "{{ remote_jar_path }}"
        owner: root
        group: root
        mode: '0755'
#      notify: restart the spring boot application

#    - name: Reload systemd daemon if service file is updated
#      systemd:
#        daemon_reload: yes

#  handlers:
#    - name: restart the spring boot application
#      systemd:
#        name: "{{ service_name }}"
#        state: restarted
#        daemon_reload: yes
