server:
  port: 9069

spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: octopus6#Bid7
    url: jdbc:mysql://132.226.130.209:3306/micro
    username: techteam
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
      
