server:
  port: 9898


security:
  oauth2:
    client: 
      clientId: 6134235546645251 
      clientSecret: 318d6b56ab6eed21242410bc348fcd7ca 
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me