errorCodes:
  '403': your credentials are wrong
  '500': internal server error
  '406' : Some unexpected error has occured please contact your support team
  '407' : Some unexpected error has occured please contact your support team
 
 
defaultTokenExpirationTime : 15
  
server:
  port: 9084
  
  
spring:
  application:
    name: JWT-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: octopus6#Bid7
    url: jdbc:mysql://132.226.130.209:3306/micro
    username: techteam
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

# application.yml
management:
  endpoints:
    web:
      exposure:
        include: prometheus
